
import { Metadata } from "next"
import { ReactNode } from "react"


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function Layout({ children }: {
    children: ReactNode
}) {
    return (
        <>
            <div style={{
                width: "98%",
                margin: "1rem 1%"
            }}>
                {children}
            </div>
        </>
    )
}