import { Metadata } from 'next'
import { ReactNode } from 'react'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function Layout({ children }: { children: ReactNode }) {
  return <div style={{ maxWidth: '1400px', margin: '1rem auto' }}>{children}</div>
}
