import type { Metadata } from 'next'
import BodyWrapper from '@/components/layout/body-wrapper'
import InnerWrapper from '@/components/layout/inner-wrapper'
import DashboardSidebar from '@/components/layout/dashboard-sidebar'
import DashboardNavbar from '@/components/layout/dashboard-navbar'
import RecoilRootWrapper from '@/components/recoil-root-wrapper'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function BackOfficeLayout({ children }: { children: React.ReactNode }) {
  return (
    <RecoilRootWrapper>
      <DashboardSidebar />
      <BodyWrapper>
        <DashboardNavbar />
        <InnerWrapper>{children}</InnerWrapper>
      </BodyWrapper>
    </RecoilRootWrapper>
  )
}
